spring:
  datasource:
    url: jdbc:mysql://localhost:13306/subway?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:/schema.sql
      mode: always
